---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
spec: {}
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kyverno
  namespace: kyverno
  annotations:
    apps.open-cluster-management.io/deployables: ''
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kyverno
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: kyverno-subscription-1
  namespace: kyverno
  annotations: {}
  labels:
    app: kyverno
    app.kubernetes.io/part-of: kyverno
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  name: kyverno
  channel: kyverno-channel/kyverno
  packageOverrides:
    - packageAlias: kyverno
      packageName: kyverno
      packageOverrides:
      - path: spec
        value:
            extraArgs:
              - '--clientRateLimitQPS=20'
              - '--clientRateLimitBurst=50'
            resources:
              limits:
                memory: 768Mi
            initResources:
              limits:
                memory: 512Mi
            livenessProbe:
              initialDelaySeconds: 45
              periodSeconds: 40
            readinessProbe:
              initialDelaySeconds: 35
              periodSeconds: 20
            securityContext: null
  placement:
    placementRef:
      name: kyverno-placement-1
      kind: PlacementRule
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: kyverno-placement-1
  namespace: kyverno
  labels:
    app: kyverno
spec:
  clusterSelector:
    matchLabels:
      install: kyverno 
--- 
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: kyverno
  namespace: kyverno-channel
spec:
  pathname: https://b-alazard.github.io/acm-kyverno/
  type: HelmRepo
